// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqmzhldfcotgxvwlmjxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxbXpobGRmY290Z3h2d2xtanhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyODk2ODYsImV4cCI6MjA2ODg2NTY4Nn0.sbnoFgrPAhQeXWfw61ZpPt-DTi9Kfb-O2kP8l9S8tcU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});